--------------------------------------------------------
--  Fichier créé - lundi-avril-24-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."COMMANDE" 
   (	"ID" NUMBER(10,0), 
	"CODE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"ID_CUSTOMER" NUMBER(10,0) DEFAULT NULL, 
	"DATE_ORDERING" TIMESTAMP (0) DEFAULT NULL, 
	"DATE_DELIVERED" TIMESTAMP (0) DEFAULT NULL, 
	"STATE" NUMBER(3,0) DEFAULT 0, 
	"SHIPPING_ADDRESS" VARCHAR2(50 BYTE), 
	"BILLING_ADDRESS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMANDE_PRODUCT
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."COMMANDE_PRODUCT" 
   (	"ID" NUMBER(10,0), 
	"ID_COMMANDE" NUMBER(10,0) DEFAULT NULL, 
	"ID_PRODUCT" NUMBER(10,0) DEFAULT NULL, 
	"QUANTITY" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMANDE_SERVICE
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."COMMANDE_SERVICE" 
   (	"ID" NUMBER(10,0), 
	"ID_COMMANDE" NUMBER(10,0) DEFAULT NULL, 
	"ID_SERVICE" NUMBER(10,0) DEFAULT NULL, 
	"QUANTITY" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."COMMENTS" 
   (	"ID" NUMBER(10,0), 
	"ID_AUTHOR" NUMBER(10,0) DEFAULT NULL, 
	"DATE_POSTED" TIMESTAMP (0) DEFAULT SYSTIMESTAMP, 
	"CONTENT" VARCHAR2(500 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS_PRODUCT
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."COMMENTS_PRODUCT" 
   (	"ID" NUMBER(10,0), 
	"ID_COMMENT" NUMBER(10,0) DEFAULT NULL, 
	"ID_PRODUCT" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS_SERVICE
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."COMMENTS_SERVICE" 
   (	"ID" NUMBER(10,0), 
	"ID_COMMENT" NUMBER(10,0) DEFAULT NULL, 
	"ID_SERVICE" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONNECTION
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."CONNECTION" 
   (	"ID" NUMBER(10,0), 
	"LOGIN_TIME" TIMESTAMP (0) DEFAULT NULL, 
	"PERSON_ID" NUMBER(10,0) DEFAULT NULL, 
	"PERSON_ID_IP_ADDRESS" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"PERSON_TYPE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"LOGOUT_TIME" TIMESTAMP (0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVALUATION
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."EVALUATION" 
   (	"ID" NUMBER(10,0), 
	"ID_PERSON" NUMBER(10,0) DEFAULT NULL, 
	"ID_JURY" NUMBER(10,0) DEFAULT NULL, 
	"NOTE" BINARY_DOUBLE DEFAULT NULL, 
	"COMMENTS" VARCHAR2(500 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICE
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."INVOICE" 
   (	"ID" NUMBER(10,0), 
	"CODE_INVOICE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"CREATION_DATE" TIMESTAMP (0) DEFAULT NULL, 
	"DELIVERED_DATE" TIMESTAMP (0) DEFAULT NULL, 
	"TYPE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"TOTAL_PRICE" BINARY_DOUBLE DEFAULT NULL, 
	"HEADER_MESSAGE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"FOOTER_MESSAGE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"LEGAL_MESSAGE" VARCHAR2(45 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICE_PERSON
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."INVOICE_PERSON" 
   (	"ID" NUMBER(10,0), 
	"ID_INVOICE" NUMBER(10,0) DEFAULT NULL, 
	"ID_PERSON" NUMBER(10,0) DEFAULT NULL, 
	"PERSON_NAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"PERSON_ADDRESS" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"PERSON_SURNAME" VARCHAR2(45 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICE_PRODUCT
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."INVOICE_PRODUCT" 
   (	"ID" NUMBER(10,0), 
	"ID_INVOICE" NUMBER(10,0) DEFAULT NULL, 
	"ID_PRODUCT" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICE_SERVICE
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."INVOICE_SERVICE" 
   (	"ID" NUMBER(10,0), 
	"ID_INVOICE" NUMBER(10,0) DEFAULT NULL, 
	"ID_SERVICE" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MESSAGE
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."MESSAGE" 
   (	"ID" NUMBER(10,0), 
	"ID_SENDER" NUMBER(10,0) DEFAULT NULL, 
	"ID_RECEIVER" NUMBER(10,0) DEFAULT NULL, 
	"CONTENT" VARCHAR2(500 BYTE) DEFAULT NULL, 
	"SENT_DATE" TIMESTAMP (0) DEFAULT SYSTIMESTAMP, 
	"RECEIVE_DATE" TIMESTAMP (0) DEFAULT NULL, 
	"READ_DATE" TIMESTAMP (0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."PERSON" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"SECOND_NAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"SURNAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"SECOND_SURNAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"PROFESSION" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"DATE_INSCRIPTION" TIMESTAMP (0) DEFAULT NULL, 
	"PASSWORD" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"EMAIL" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"PHONE_NUMBER" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"TEL_NUMBER" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"FACEBOOK_ID" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"TWITTER_ID" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"INSTAGRAM_ID" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"LINKEDIN_ID" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"ACCOUNT_PICTURE" BLOB, 
	"STREET_NUMBER" NUMBER(10,0) DEFAULT NULL, 
	"STREET_NAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"CITY_NAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"COUNTRY_NAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"POSTAL_CODE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"LAST_CONNECTION" NUMBER(10,0) DEFAULT NULL, 
	"FUNCTION" VARCHAR2(45 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ACCOUNT_PICTURE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."PRODUCT" 
   (	"ID" NUMBER(10,0), 
	"CODE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"NAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"DESCRIPTION" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"PRICE" BINARY_DOUBLE DEFAULT NULL, 
	"MAIN_IMAGE" BLOB, 
	"TYPE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"ID_PROVIDER" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("MAIN_IMAGE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table PRODUCT_COMPONENT
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."PRODUCT_COMPONENT" 
   (	"ID" NUMBER(10,0), 
	"ID_COMPONED" NUMBER(10,0) DEFAULT NULL, 
	"ID_COMPONENT" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_SERVICE
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."PRODUCT_SERVICE" 
   (	"ID" NUMBER(10,0), 
	"ID_PRODUCT" NUMBER(10,0) DEFAULT NULL, 
	"ID_SERVICE" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."SERVICE" 
   (	"ID" NUMBER(10,0), 
	"CODE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"NAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"DESCRIPTION" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"PRICE" BINARY_DOUBLE DEFAULT NULL, 
	"MAIN_IMAGE" BLOB, 
	"ID_PROVIDER" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("MAIN_IMAGE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table SERVICE_COMPONENT
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."SERVICE_COMPONENT" 
   (	"ID" NUMBER(10,0), 
	"ID_SERVICE" NUMBER(10,0) DEFAULT NULL, 
	"ID_COMPONENT" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICE_PRODUCT
--------------------------------------------------------

  CREATE TABLE "PAPFOOD"."SERVICE_PRODUCT" 
   (	"ID" NUMBER(10,0), 
	"ID_SERVICE" NUMBER(10,0) DEFAULT NULL, 
	"ID_PRODUCT" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence COMMANDE_PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."COMMANDE_PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMANDE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."COMMANDE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMANDE_SERVICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."COMMANDE_SERVICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMENTS_PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."COMMENTS_PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."COMMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMENTS_SERVICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."COMMENTS_SERVICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONNECTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."CONNECTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EVALUATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."EVALUATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INVOICE_PERSON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."INVOICE_PERSON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INVOICE_PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."INVOICE_PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INVOICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."INVOICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INVOICE_SERVICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."INVOICE_SERVICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MESSAGE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."MESSAGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."ORDER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PERSON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."PERSON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_COMPONENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."PRODUCT_COMPONENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_SERVICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."PRODUCT_SERVICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SERVICE_COMPONENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."SERVICE_COMPONENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SERVICE_PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."SERVICE_PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SERVICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAPFOOD"."SERVICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into PAPFOOD.COMMANDE
SET DEFINE OFF;
REM INSERTING into PAPFOOD.COMMANDE_PRODUCT
SET DEFINE OFF;
REM INSERTING into PAPFOOD.COMMANDE_SERVICE
SET DEFINE OFF;
REM INSERTING into PAPFOOD.COMMENTS
SET DEFINE OFF;
REM INSERTING into PAPFOOD.COMMENTS_PRODUCT
SET DEFINE OFF;
REM INSERTING into PAPFOOD.COMMENTS_SERVICE
SET DEFINE OFF;
REM INSERTING into PAPFOOD.CONNECTION
SET DEFINE OFF;
Insert into PAPFOOD.CONNECTION (ID,LOGIN_TIME,PERSON_ID,PERSON_ID_IP_ADDRESS,PERSON_TYPE,LOGOUT_TIME) values ('1',to_timestamp('16/04/17 12:57:01,000000000','DD/MM/RR HH24:MI:SSXFF'),'71','Noubissi','Mbengue',to_timestamp('16/04/17 12:57:25,000000000','DD/MM/RR HH24:MI:SSXFF'));
REM INSERTING into PAPFOOD.EVALUATION
SET DEFINE OFF;
REM INSERTING into PAPFOOD.INVOICE
SET DEFINE OFF;
REM INSERTING into PAPFOOD.INVOICE_PERSON
SET DEFINE OFF;
REM INSERTING into PAPFOOD.INVOICE_PRODUCT
SET DEFINE OFF;
REM INSERTING into PAPFOOD.INVOICE_SERVICE
SET DEFINE OFF;
REM INSERTING into PAPFOOD.MESSAGE
SET DEFINE OFF;
Insert into PAPFOOD.MESSAGE (ID,ID_SENDER,ID_RECEIVER,CONTENT,SENT_DATE,RECEIVE_DATE,READ_DATE) values ('2','71','59','blablabla',to_timestamp('17/04/17 05:43:09,000000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('17/04/17 07:48:52,000000000','DD/MM/RR HH24:MI:SSXFF'),null);
REM INSERTING into PAPFOOD.PERSON
SET DEFINE OFF;
Insert into PAPFOOD.PERSON (ID,NAME,SECOND_NAME,SURNAME,SECOND_SURNAME,PROFESSION,DATE_INSCRIPTION,PASSWORD,EMAIL,PHONE_NUMBER,TEL_NUMBER,FACEBOOK_ID,TWITTER_ID,INSTAGRAM_ID,LINKEDIN_ID,STREET_NUMBER,STREET_NAME,CITY_NAME,COUNTRY_NAME,POSTAL_CODE,LAST_CONNECTION,FUNCTION) values ('63','maf',null,null,null,null,to_timestamp('10/04/17 02:31:57,000000000','DD/MM/RR HH24:MI:SSXFF'),'maf','maf@maf.com',null,null,null,null,null,null,null,null,null,null,null,null,'admin');
Insert into PAPFOOD.PERSON (ID,NAME,SECOND_NAME,SURNAME,SECOND_SURNAME,PROFESSION,DATE_INSCRIPTION,PASSWORD,EMAIL,PHONE_NUMBER,TEL_NUMBER,FACEBOOK_ID,TWITTER_ID,INSTAGRAM_ID,LINKEDIN_ID,STREET_NUMBER,STREET_NAME,CITY_NAME,COUNTRY_NAME,POSTAL_CODE,LAST_CONNECTION,FUNCTION) values ('81','Testmaf',null,null,null,null,to_timestamp('16/04/17 16:17:47,000000000','DD/MM/RR HH24:MI:SSXFF'),'POdUMaBBOwKonfSiG2rFipzRgfdtzffaSx3jjnX6j3jzZjCeTVGE7g==','test@test.com',null,null,null,null,null,null,null,null,null,null,null,null,'User');
Insert into PAPFOOD.PERSON (ID,NAME,SECOND_NAME,SURNAME,SECOND_SURNAME,PROFESSION,DATE_INSCRIPTION,PASSWORD,EMAIL,PHONE_NUMBER,TEL_NUMBER,FACEBOOK_ID,TWITTER_ID,INSTAGRAM_ID,LINKEDIN_ID,STREET_NUMBER,STREET_NAME,CITY_NAME,COUNTRY_NAME,POSTAL_CODE,LAST_CONNECTION,FUNCTION) values ('87','Testmafazertyqsdfgui',null,null,null,null,to_timestamp('16/04/17 16:52:26,000000000','DD/MM/RR HH24:MI:SSXFF'),'VcyYm02YSdwY6Zsrlv3MJV0F4ziriFdXJEitd5we83ROADKSJm8xTg==','azerty@gmailazetyui.com',null,null,null,null,null,null,null,null,null,null,null,null,'User');
Insert into PAPFOOD.PERSON (ID,NAME,SECOND_NAME,SURNAME,SECOND_SURNAME,PROFESSION,DATE_INSCRIPTION,PASSWORD,EMAIL,PHONE_NUMBER,TEL_NUMBER,FACEBOOK_ID,TWITTER_ID,INSTAGRAM_ID,LINKEDIN_ID,STREET_NUMBER,STREET_NAME,CITY_NAME,COUNTRY_NAME,POSTAL_CODE,LAST_CONNECTION,FUNCTION) values ('57','maf',null,null,null,null,to_timestamp('10/04/17 02:03:06,000000000','DD/MM/RR HH24:MI:SSXFF'),'maf','maf@maf.com',null,null,null,null,null,null,null,null,null,null,null,null,'admin');
Insert into PAPFOOD.PERSON (ID,NAME,SECOND_NAME,SURNAME,SECOND_SURNAME,PROFESSION,DATE_INSCRIPTION,PASSWORD,EMAIL,PHONE_NUMBER,TEL_NUMBER,FACEBOOK_ID,TWITTER_ID,INSTAGRAM_ID,LINKEDIN_ID,STREET_NUMBER,STREET_NAME,CITY_NAME,COUNTRY_NAME,POSTAL_CODE,LAST_CONNECTION,FUNCTION) values ('64','rat',null,null,null,null,to_timestamp('10/04/17 03:39:27,000000000','DD/MM/RR HH24:MI:SSXFF'),'dZx57Z+UinUwXR5/xSyGw/dk/y9UeGmaB8kM7N0Xz+zMZWkWkKFnzg==','rat@rat.com',null,null,null,null,null,null,null,null,null,null,null,null,'User');
Insert into PAPFOOD.PERSON (ID,NAME,SECOND_NAME,SURNAME,SECOND_SURNAME,PROFESSION,DATE_INSCRIPTION,PASSWORD,EMAIL,PHONE_NUMBER,TEL_NUMBER,FACEBOOK_ID,TWITTER_ID,INSTAGRAM_ID,LINKEDIN_ID,STREET_NUMBER,STREET_NAME,CITY_NAME,COUNTRY_NAME,POSTAL_CODE,LAST_CONNECTION,FUNCTION) values ('71',null,null,null,null,null,to_timestamp('10/04/17 13:45:58,000000000','DD/MM/RR HH24:MI:SSXFF'),'Ap3WAywSu0ZFZHreZGPW4B/U+43L5uTk7C38JfA+xRCJjwJZ4pfaNg==',null,null,null,null,null,null,null,null,null,'Nice','France',null,'1','Admin');
Insert into PAPFOOD.PERSON (ID,NAME,SECOND_NAME,SURNAME,SECOND_SURNAME,PROFESSION,DATE_INSCRIPTION,PASSWORD,EMAIL,PHONE_NUMBER,TEL_NUMBER,FACEBOOK_ID,TWITTER_ID,INSTAGRAM_ID,LINKEDIN_ID,STREET_NUMBER,STREET_NAME,CITY_NAME,COUNTRY_NAME,POSTAL_CODE,LAST_CONNECTION,FUNCTION) values ('59','maf',null,null,null,null,to_timestamp('10/04/17 02:15:18,000000000','DD/MM/RR HH24:MI:SSXFF'),'maf','maf@maf.com',null,null,null,null,null,null,null,null,null,null,null,null,'admin');
Insert into PAPFOOD.PERSON (ID,NAME,SECOND_NAME,SURNAME,SECOND_SURNAME,PROFESSION,DATE_INSCRIPTION,PASSWORD,EMAIL,PHONE_NUMBER,TEL_NUMBER,FACEBOOK_ID,TWITTER_ID,INSTAGRAM_ID,LINKEDIN_ID,STREET_NUMBER,STREET_NAME,CITY_NAME,COUNTRY_NAME,POSTAL_CODE,LAST_CONNECTION,FUNCTION) values ('60','maf',null,null,null,null,to_timestamp('10/04/17 02:16:30,000000000','DD/MM/RR HH24:MI:SSXFF'),'maf','maf@maf.com',null,null,null,null,null,null,null,null,null,null,null,null,'admin');
Insert into PAPFOOD.PERSON (ID,NAME,SECOND_NAME,SURNAME,SECOND_SURNAME,PROFESSION,DATE_INSCRIPTION,PASSWORD,EMAIL,PHONE_NUMBER,TEL_NUMBER,FACEBOOK_ID,TWITTER_ID,INSTAGRAM_ID,LINKEDIN_ID,STREET_NUMBER,STREET_NAME,CITY_NAME,COUNTRY_NAME,POSTAL_CODE,LAST_CONNECTION,FUNCTION) values ('62','maf',null,null,null,null,to_timestamp('10/04/17 02:29:30,000000000','DD/MM/RR HH24:MI:SSXFF'),'maf','maf@maf.com',null,null,null,null,null,null,null,null,null,null,null,null,'admin');
REM INSERTING into PAPFOOD.PRODUCT
SET DEFINE OFF;
REM INSERTING into PAPFOOD.PRODUCT_COMPONENT
SET DEFINE OFF;
REM INSERTING into PAPFOOD.PRODUCT_SERVICE
SET DEFINE OFF;
REM INSERTING into PAPFOOD.SERVICE
SET DEFINE OFF;
REM INSERTING into PAPFOOD.SERVICE_COMPONENT
SET DEFINE OFF;
REM INSERTING into PAPFOOD.SERVICE_PRODUCT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger COMMANDE_PRODUCT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."COMMANDE_PRODUCT_SEQ_TR" 
 BEFORE INSERT ON papfood.commande_product FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.commande_product_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."COMMANDE_PRODUCT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMANDE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."COMMANDE_SEQ_TR" 
 BEFORE INSERT ON papfood.commande FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.commande_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."COMMANDE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMANDE_SERVICE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."COMMANDE_SERVICE_SEQ_TR" 
 BEFORE INSERT ON papfood.commande_service FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.commande_service_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."COMMANDE_SERVICE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMENTS_PRODUCT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."COMMENTS_PRODUCT_SEQ_TR" 
 BEFORE INSERT ON papfood.comments_product FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.comments_product_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."COMMENTS_PRODUCT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMENTS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."COMMENTS_SEQ_TR" 
 BEFORE INSERT ON papfood.comments FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.comments_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."COMMENTS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMENTS_SERVICE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."COMMENTS_SERVICE_SEQ_TR" 
 BEFORE INSERT ON papfood.comments_service FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.comments_service_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."COMMENTS_SERVICE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONNECTION_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."CONNECTION_SEQ_TR" 
 BEFORE INSERT ON papfood.connection FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.connection_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."CONNECTION_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EVALUATION_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."EVALUATION_SEQ_TR" 
 BEFORE INSERT ON papfood.evaluation FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.evaluation_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."EVALUATION_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INVOICE_PERSON_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."INVOICE_PERSON_SEQ_TR" 
 BEFORE INSERT ON papfood.invoice_person FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.invoice_person_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."INVOICE_PERSON_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INVOICE_PRODUCT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."INVOICE_PRODUCT_SEQ_TR" 
 BEFORE INSERT ON papfood.invoice_product FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.invoice_product_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."INVOICE_PRODUCT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INVOICE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."INVOICE_SEQ_TR" 
 BEFORE INSERT ON papfood.invoice FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.invoice_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."INVOICE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INVOICE_SERVICE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."INVOICE_SERVICE_SEQ_TR" 
 BEFORE INSERT ON papfood.invoice_service FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.invoice_service_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;

/
ALTER TRIGGER "PAPFOOD"."INVOICE_SERVICE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MESSAGE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."MESSAGE_SEQ_TR" 
 BEFORE INSERT ON papfood.message FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.message_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;

/
ALTER TRIGGER "PAPFOOD"."MESSAGE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PERSON_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."PERSON_SEQ_TR" 
 BEFORE INSERT ON papfood.person FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.person_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."PERSON_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_COMPONENT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."PRODUCT_COMPONENT_SEQ_TR" 
 BEFORE INSERT ON papfood.product_component FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.product_component_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."PRODUCT_COMPONENT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."PRODUCT_SEQ_TR" 
 BEFORE INSERT ON papfood.product FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.product_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."PRODUCT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_SERVICE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."PRODUCT_SERVICE_SEQ_TR" 
 BEFORE INSERT ON papfood.product_service FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.product_service_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."PRODUCT_SERVICE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICE_COMPONENT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."SERVICE_COMPONENT_SEQ_TR" 
 BEFORE INSERT ON papfood.service_component FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.service_component_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."SERVICE_COMPONENT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICE_PRODUCT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."SERVICE_PRODUCT_SEQ_TR" 
 BEFORE INSERT ON papfood.service_product FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.service_product_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."SERVICE_PRODUCT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PAPFOOD"."SERVICE_SEQ_TR" 
 BEFORE INSERT ON papfood.service FOR EACH ROW
  WHEN (NEW.Id IS NULL) BEGIN
 SELECT papfood.service_seq.NEXTVAL INTO :NEW.Id FROM DUAL;
END;
/
ALTER TRIGGER "PAPFOOD"."SERVICE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table INVOICE_PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."INVOICE_PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."INVOICE_PRODUCT" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_PRODUCT" ADD CHECK (id_invoice > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_PRODUCT" ADD CHECK (id_product > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_PRODUCT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS_PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMENTS_PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."COMMENTS_PRODUCT" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS_PRODUCT" ADD CHECK (id_comment > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS_PRODUCT" ADD CHECK (id_product > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS_PRODUCT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVALUATION
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."EVALUATION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."EVALUATION" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."EVALUATION" ADD CHECK (id_person > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."EVALUATION" ADD CHECK (id_jury > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."EVALUATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMANDE_PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMANDE_PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."COMMANDE_PRODUCT" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_PRODUCT" ADD CHECK (id_commande > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_PRODUCT" ADD CHECK (id_product > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_PRODUCT" ADD CHECK (quantity > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_PRODUCT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."PRODUCT_SERVICE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."PRODUCT_SERVICE" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PRODUCT_SERVICE" ADD CHECK (id_product > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PRODUCT_SERVICE" ADD CHECK (id_service > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PRODUCT_SERVICE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMANDE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."COMMANDE" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE" ADD CHECK (id_customer > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE" MODIFY ("STATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE_SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMANDE_SERVICE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."COMMANDE_SERVICE" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_SERVICE" ADD CHECK (id_commande > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_SERVICE" ADD CHECK (id_service > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_SERVICE" ADD CHECK (quantity > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_SERVICE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS_SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMENTS_SERVICE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."COMMENTS_SERVICE" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS_SERVICE" ADD CHECK (id_comment > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS_SERVICE" ADD CHECK (id_service > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS_SERVICE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVOICE_SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."INVOICE_SERVICE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."INVOICE_SERVICE" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_SERVICE" ADD CHECK (id_invoice > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_SERVICE" ADD CHECK (id_service > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_SERVICE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVOICE_PERSON
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."INVOICE_PERSON" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."INVOICE_PERSON" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_PERSON" ADD CHECK (id_invoice > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_PERSON" ADD CHECK (id_person > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_PERSON" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."INVOICE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."INVOICE" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMENTS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."COMMENTS" MODIFY ("DATE_POSTED" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."COMMENTS" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS" ADD CHECK (id_author > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONNECTION
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."CONNECTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."CONNECTION" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."CONNECTION" ADD CHECK (person_id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."CONNECTION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."PERSON" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."PERSON" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PERSON" ADD CHECK (street_number > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PERSON" ADD CHECK (last_connection > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PERSON" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICE_COMPONENT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."SERVICE_COMPONENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."SERVICE_COMPONENT" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."SERVICE_COMPONENT" ADD CHECK (id_service > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."SERVICE_COMPONENT" ADD CHECK (id_component > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."SERVICE_COMPONENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICE_PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."SERVICE_PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."SERVICE_PRODUCT" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."SERVICE_PRODUCT" ADD CHECK (id_service > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."SERVICE_PRODUCT" ADD CHECK (id_product > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."SERVICE_PRODUCT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MESSAGE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."MESSAGE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."MESSAGE" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."MESSAGE" ADD CHECK (id_sender > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."MESSAGE" ADD CHECK (id_receiver > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."MESSAGE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."SERVICE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."SERVICE" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."SERVICE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."PRODUCT" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PRODUCT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_COMPONENT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."PRODUCT_COMPONENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PAPFOOD"."PRODUCT_COMPONENT" ADD CHECK (Id > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PRODUCT_COMPONENT" ADD CHECK (id_componed > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PRODUCT_COMPONENT" ADD CHECK (id_component > 0) ENABLE;
 
  ALTER TABLE "PAPFOOD"."PRODUCT_COMPONENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMANDE" ADD CONSTRAINT "FK_COMMANDE_1" FOREIGN KEY ("ID_CUSTOMER")
	  REFERENCES "PAPFOOD"."PERSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE_PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMANDE_PRODUCT" ADD CONSTRAINT "FK_COMMANDE_PRODUCT_1" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "PAPFOOD"."COMMANDE" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_PRODUCT" ADD CONSTRAINT "FK_COMMANDE_PRODUCT_2" FOREIGN KEY ("ID_PRODUCT")
	  REFERENCES "PAPFOOD"."PRODUCT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE_SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMANDE_SERVICE" ADD CONSTRAINT "FK_COMMANDE_SERVICE_1" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "PAPFOOD"."COMMANDE" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMANDE_SERVICE" ADD CONSTRAINT "FK_COMMANDE_SERVICE_2" FOREIGN KEY ("ID_SERVICE")
	  REFERENCES "PAPFOOD"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS_PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMENTS_PRODUCT" ADD CONSTRAINT "FK_COMMENTS_PRODUCT_1" FOREIGN KEY ("ID_COMMENT")
	  REFERENCES "PAPFOOD"."COMMENTS" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS_PRODUCT" ADD CONSTRAINT "FK_COMMENTS_PRODUCT_2" FOREIGN KEY ("ID_PRODUCT")
	  REFERENCES "PAPFOOD"."PRODUCT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS_SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."COMMENTS_SERVICE" ADD CONSTRAINT "FK_COMMENTS_SERVICE_1" FOREIGN KEY ("ID_COMMENT")
	  REFERENCES "PAPFOOD"."COMMENTS" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."COMMENTS_SERVICE" ADD CONSTRAINT "FK_COMMENTS_SERVICE_2" FOREIGN KEY ("ID_SERVICE")
	  REFERENCES "PAPFOOD"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONNECTION
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."CONNECTION" ADD CONSTRAINT "FK_CONNECTION_1" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "PAPFOOD"."PERSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVALUATION
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."EVALUATION" ADD CONSTRAINT "FK_EVALUATION_1" FOREIGN KEY ("ID_PERSON")
	  REFERENCES "PAPFOOD"."PERSON" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."EVALUATION" ADD CONSTRAINT "FK_EVALUATION_2" FOREIGN KEY ("ID_JURY")
	  REFERENCES "PAPFOOD"."PERSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE_PERSON
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."INVOICE_PERSON" ADD CONSTRAINT "FK_INVOICE_PERSON_1" FOREIGN KEY ("ID_INVOICE")
	  REFERENCES "PAPFOOD"."INVOICE" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_PERSON" ADD CONSTRAINT "FK_INVOICE_PERSON_2" FOREIGN KEY ("ID_PERSON")
	  REFERENCES "PAPFOOD"."PERSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE_PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."INVOICE_PRODUCT" ADD CONSTRAINT "FK_INVOICE_PRODUCT_1" FOREIGN KEY ("ID_INVOICE")
	  REFERENCES "PAPFOOD"."INVOICE" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_PRODUCT" ADD CONSTRAINT "FK_INVOICE_PRODUCT_2" FOREIGN KEY ("ID_PRODUCT")
	  REFERENCES "PAPFOOD"."PRODUCT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE_SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."INVOICE_SERVICE" ADD CONSTRAINT "FK_INVOICE_SERVICE_1" FOREIGN KEY ("ID_INVOICE")
	  REFERENCES "PAPFOOD"."INVOICE" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."INVOICE_SERVICE" ADD CONSTRAINT "FK_INVOICE_SERVICE_2" FOREIGN KEY ("ID_SERVICE")
	  REFERENCES "PAPFOOD"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESSAGE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."MESSAGE" ADD CONSTRAINT "FK_MESSAGE_1" FOREIGN KEY ("ID_SENDER")
	  REFERENCES "PAPFOOD"."PERSON" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."MESSAGE" ADD CONSTRAINT "FK_MESSAGE_2" FOREIGN KEY ("ID_RECEIVER")
	  REFERENCES "PAPFOOD"."PERSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."PERSON" ADD CONSTRAINT "FK_PERSON_1" FOREIGN KEY ("LAST_CONNECTION")
	  REFERENCES "PAPFOOD"."CONNECTION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."PRODUCT" ADD CONSTRAINT "FK_PRODUCT_1" FOREIGN KEY ("ID_PROVIDER")
	  REFERENCES "PAPFOOD"."PERSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_COMPONENT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."PRODUCT_COMPONENT" ADD CONSTRAINT "FK_PRODUCT_COMPONENT_1" FOREIGN KEY ("ID_COMPONED")
	  REFERENCES "PAPFOOD"."PRODUCT" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."PRODUCT_COMPONENT" ADD CONSTRAINT "FK_PRODUCT_COMPONENT_2" FOREIGN KEY ("ID_COMPONENT")
	  REFERENCES "PAPFOOD"."PRODUCT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."PRODUCT_SERVICE" ADD CONSTRAINT "FK_PRODUCT_SERVICE_1" FOREIGN KEY ("ID_PRODUCT")
	  REFERENCES "PAPFOOD"."PRODUCT" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."PRODUCT_SERVICE" ADD CONSTRAINT "FK_PRODUCT_SERVICE_2" FOREIGN KEY ("ID_SERVICE")
	  REFERENCES "PAPFOOD"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."SERVICE" ADD CONSTRAINT "FK_SERVICE_1" FOREIGN KEY ("ID_PROVIDER")
	  REFERENCES "PAPFOOD"."PERSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_COMPONENT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."SERVICE_COMPONENT" ADD CONSTRAINT "FK_SERVICE_COMPONENT_1" FOREIGN KEY ("ID_SERVICE")
	  REFERENCES "PAPFOOD"."SERVICE" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."SERVICE_COMPONENT" ADD CONSTRAINT "FK_SERVICE_COMPONENT_2" FOREIGN KEY ("ID_COMPONENT")
	  REFERENCES "PAPFOOD"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_PRODUCT
--------------------------------------------------------

  ALTER TABLE "PAPFOOD"."SERVICE_PRODUCT" ADD CONSTRAINT "FK_SERVICE_PRODUCT_1" FOREIGN KEY ("ID_SERVICE")
	  REFERENCES "PAPFOOD"."SERVICE" ("ID") ENABLE;
 
  ALTER TABLE "PAPFOOD"."SERVICE_PRODUCT" ADD CONSTRAINT "FK_SERVICE_PRODUCT_2" FOREIGN KEY ("ID_PRODUCT")
	  REFERENCES "PAPFOOD"."PRODUCT" ("ID") ENABLE;
